CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category_id INTEGER DEFAULT 0,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'drink',
  cost REAL DEFAULT 0,
  price REAL DEFAULT 0,
  is_active INTEGER DEFAULT 1
);